name: "MySQL CI/CD Pipeline"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_USER: developer
          MYSQL_DATABASE: project_db
          MYSQL_PASSWORD: ${{ secrets.DATABASEPASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.ROOTPASSWORD }}
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install dependencies and necessary tools
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Wait for MySQL to be ready
        run: |
          while ! mysqladmin ping -h 127.0.0.1 -u root -p${{ secrets.ROOTPASSWORD }} --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 2
          done
          echo "MySQL is ready!"
    
      - name: Initial Schema Deployment
        run: |
          mysql -h 127.0.0.1 -u developer -p${{ secrets.DATABASEPASSWORD }} project_db < sql/create_table.sql
    
      - name: Schema Update
        run: |
          mysql -h 127.0.0.1 -u developer -p${{ secrets.DATABASEPASSWORD }} project_db < sql/schema_update.sql

      - name: Data Seeding
        run: |
          mysql -h 127.0.0.1 -u developer -p${{ secrets.DATABASEPASSWORD }} project_db < sql/seed_data.sql

      - name: Concurrent Query Execution
        env:    
          DB_HOST: 127.0.0.1
          DB_USER: developer
          DB_PASSWORD: ${{ secrets.DATABASEPASSWORD }}
          DB_NAME: project_db
        run: |
          python scripts/multi_thread_queries.py

      - name: Validation Step
        run: |
          mysql -h 127.0.0.1 -u developer -p${{ secrets.DATABASEPASSWORD }} project_db < sql/validation.sql

      - name: Optimize Table for performance improvement.
        run: |
          mysql -h 127.0.0.1 -u developer -p${{ secrets.DATABASEPASSWORD }} project_db < sql/table_optimization.sql

      - name: Validation Ater Optimization 
        run: |
          mysql -h 127.0.0.1 -u developer -p${{ secrets.DATABASEPASSWORD }} project_db < sql/validation.sql
